### PR TITLE
Sec

### LINKED ISSUE #30: Security issues
Capture215

Capture218

Capture220

Then `npm audit fix --force`

Capture221

### PR DESCRIPTION
**Pull request by peterennis**
Fix #30 

Husky bites too much.

Eventually:
Capture233
Capture232

### CODE REVIEW

**Comment by peterennis** [comment]
From:
Capture215

To:
Capture221

**Comment by peterennis** [comment]
CircleCI test fail likely due to jest version upgrade:

Capture547

Capture546

**Comment by edgarordonez** [comment]
Hello @peterennis 

I've been trying to update jest to `24.8.0`, and then run the test locally, but automatically the jest version was switched to `23.6.0`. I think that it could be something related to `@stencil/core`, but I'm not sure. WDYT? I found this: [stencil/issues/1450](https://github.com/ionic-team/stencil/issues/1450)

Also, we can remove yarn ofc, no problem from my side, but I've set husky to be "safe" about commit messages and pre-push scripts. Have you got some better alternative?

Thanks for all! :)

**Comment by peterennis** [comment]
@edgarordonez 

The deps branch is made from sec.

Here:

https://github.com/peterennis/d3-stencil/blob/deps/package.json

Capture241

Jest updates OK. The problem is going to 18.1

I may try some newer versions after 16.4

**Comment by peterennis** [comment]
@edgarordonez 

The real challenge is this:

https://github.com/ionic-team/stencil/issues/1464
https://github.com/ionic-team/stencil/commit/89b5e81e040feca41db555a6c995b7335e55a113

Read breaking changes and weep (for a while):
https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md

I pushed the deps in a test and the result is this:

Capture234

I will try some incremental changes to find the breaking point then
some code updates will be required and possibly open a ticket
to stencil upstream.

**Comment by peterennis** [comment]
deps branch here:

https://github.com/peterennis/d3-stencil/blob/deps/package.json

0.17.2 runs

Capture242

**Comment by peterennis** [comment]
deps branch 0.18.0 runs

Capture243

Capture244

**Comment by peterennis** [comment]
The Smoking Gun :gun:

@edgarordonez  Breaks on Stencil 0.18.1

Capture245

I will create a branch for the breakage and open a ticket upstream.

NOTE: The immediate goal should be to get it building again. Next start
a build for the 1.0.0.beta line. Running and updating tests should be tackled
at that time.

**Comment by peterennis** [comment]
0.18.1-0 runs

Capture246

**Comment by peterennis** [comment]
0.18.1-1 BROKEN

This commit: https://github.com/peterennis/d3-stencil/commit/0e1c368699994b9912745bf8afbabd57baaeeba2

Capture247

**Comment by peterennis** [comment]
@edgarordonez 
0.18.1 is borked so the PR is locked at 0.18.0
Not sure if upstream care enough but it seems they fixed it in Stencil One.
Husky added back in.
You could merge this and call it the end of the road for this version.
I do not know why coveralls fails. Maybe the tests are outdated.
I will setup a dev branch for the Stencil One line.

**Comment by peterennis** [comment]
> Hello @peterennis
> 
> I've been trying to update jest to `24.8.0`, and then run the test locally, but automatically the jest version was switched to `23.6.0`. I think that it could be something related to `@stencil/core`, but I'm not sure. WDYT? I found this: [stencil/issues/1450](https://github.com/ionic-team/stencil/issues/1450)
> 
> Also, we can remove yarn ofc, no problem from my side, but I've set husky to be "safe" about commit messages and pre-push scripts. Do you have some better alternative?
> 
> Thanks for all! :)

@edgarordonez 
Ticket here: https://github.com/ionic-team/stencil/issues/1559

**Comment by edgarordonez** [comment]
Hello @peterennis 

I wrote the same changes, and I pushed them. Thanks! 👍

**Pull request closed without merging**
